[OC-6] - Add proma banner at css,html
archis-academy/october-frontend-shopco-1 pull request #12
Opened 2024-11-15 16:32 UTC by EsraaFiliz

2024-11-15 16:49 UTC, ozcsert requested changes
Carpi isareti display:none yapabilir. 

Kucuk ekranlarda carpi isaretini kaldiralim.

2024-11-19 16:39 UTC, EsraaFiliz commented
@ozcsert Merhaba, Kontrolünüze sunarım.

2024-11-19 16:52 UTC, ozcsert requested changes
Ufak bir değişiklik istedim onun dışında eline sağlık

2024-11-19 16:52 UTC, ozcsert commented on style.css
>    width: 100%;
Çarpı işaretine bastığımızda direk displa:none ile yokedelim banner'ı.

2024-11-21 07:16 UTC, EsraaFiliz commented on style.css
>    width: 100%;
@ozcsert  Merhaba, düzenlemeyi ekledim. Kontrolünüze sunarım.

2024-11-22 16:26 UTC, merged