[OC-22] - footer yapıldı
archis-academy/october-frontend-shopco-1 pull request #5
Opened 2024-11-01 15:56 UTC by melikeaksoy555

2024-11-01 21:08 UTC, ozcsert requested changes
Onerdigim degisiklikler en az kod ile en optimal sonucu almak uzerine uygulanmis degisiklikler. Birden fazla cozum her zaman var olabilir ama en az static deger kullanarak yapilan dizaynlar hedeflenmeli. Bu seni daha az kod yazmak uzerine kosullayacaktir.

Footer'lar ince ayarlar gerektirebiliyor cunku bir cok elementi ekran kuculdukce az yere sigdirman gerekiyor. 

Genel dizaynin gayet iyi CSS'in oturmus sadece kutu modelini uygularken tecrubeye ihtiyacin var. Ozellikle projenin gereksinimlerini takip edip degiskenleri kullanman ciddiye aldiginin gostergesi. Ayrica clamp gibi ileri seviye responsive cozumlere alisman cok yarar saglayacaktir. 


Onerdigim degisiklikler disinda font renklerini degistirmek icin olabildiginde spesify etmen gerekebilir classlari css icerisinde . ornek `.footer-right ul li a {
color:var(--fnt-black)} `

kolay gelsin

2024-11-01 21:08 UTC, ozcsert commented on index.html
> +      </div>
bu Ust ve Alt kisimlari bir .footer-wrapper altina alalim ki ikisininde widthlerinin birbirlerinden bagimsiz hareket etmelerini engelleyelim. Zaten <footer> tag'i  var  ikisini de kapsayan dedigini duyar gibiyim ancak  o footer bize bir limitten ziyade genel tabloyu hazirliyor.  Bize alt ve ust ikisi icin ortak limit belirleyici bir parent lazim. Isleme koyduktan sonra daha da mantikli gelecek. 


```
.footer-wrapper {
  display: flex; 
  flex-direction: column;
  width: 100%;  ==> Kesin deger vermektense daha dinamik bir deger
  max-width: 1440px;  ==> yukariya 100% verdikten sonra asil genisligimizi stoplayan bu. bizim dizaynimizdaki 
                                             ana konteynir.
  align-items: center;
}
```

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +  font-family: var(--fnt-family-satoshi);
```
  display: flex;
  justify-content: center;
```

2024-11-01 21:08 UTC, ozcsert commented on index.html
> +            <a href="#">Career</a>
linkleri ve listelemeleri `<ul> <li>` tagleri arasina sararak kullaniyoruz. 

https://www.w3schools.com/tags/tag_ul.asp

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +  max-width: 1240px;
.footer-container {
  display: flex;
  gap: clamp(10px, 6vw, 113px);  => Cok yararli bir css fonksiyonudur. ilki minimum, ikincisi viewporta oranla deger vermek istedigimiz deger, ucuncu maximum deger, 
  width: 90%; => Kenarlara sabit padding vermektense(responsive'de ugrastirir) yuzdelerle calisip alttaki gibi yine max width ile stop koyabilirsin. Her ne  kadar kuculurse kuculsun  kenarlarda 10% bosluk kalir
  max-width: 1240px;
}

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +  gap: 113px;
gap: clamp(10px, 6vw, 113px);

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +  margin: auto;
`  width: 90%;  => ust kisimla ayni width degerini alsin diye
  max-width: 1240px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  
 `
 
 margin: auto; ya gerek yok

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +  max-width: 149px;
.footer-column {
  min-width: 130px;
} => 4 kisminda ayni hizada durmasini saglar. uygulayarak daha iyi anlayabilirsin

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +  margin-bottom: 19px;
eger bunu da clamp ile verirsen ekran kuculdugunde aralardaki gap'ler kendiliginden kuculur. bir clamp denemesi olsun senin icin.

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +  margin-bottom: 25px;
```
  width: 90%;
  max-width: 1240px;
```

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +  }
.footer-container {
    flex-direction: column;
    align-items: center;
  }
  
  sadece bunlar isimizi goruyor su asamada. ne kadar az media query kullanirsak o kadar iyi is yapmisiz demek.

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +  }
ihtiyacimiz yok

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +    flex-direction: column;
bu kismi yeni bir media query acip oraya alsak daha iyi olabilir hem butun sectionlar ayni anda column'a gecer. 
 
```
 @media (max-width: 750px) {
  .footer-right {
    flex-wrap: wrap;
    justify-content: space-around;
  }
  .footer-column {
    width: 40%;  ==> deneyerek bulunan bir deger, 750 ekran altinda ayni row'da bulunan itemlere bunu veriyorum ki daha duzgun bir dizilim olsun. 
  }
  .footer-bottom {
    flex-direction: column;
  }
}
```

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +    text-align: center;
ihtiyacimiz yok.

2024-11-01 21:08 UTC, ozcsert commented on style.css
> +  }
ihtiyacimiz yok

2024-11-01 21:08 UTC, ozcsert commented on index.html
> +        </div>
```
.payment-icons {
  text-align: center;
}
.payment-icons img {
  width: 18%;  => buraya normalde flex:1 verirsem hepsi otomatik olarak parenta gore esit genislik ile row'u doldururdu. ama flex, img'leri element olarak gormuyor. bunun icin imglarin her birini <div> altina sarmam gerekir. bu durum icin overkill olacagindan hepsine hesaben yuzde verebilirsin ki alta sarmasinlar.
}
```

2024-11-09 20:00 UTC, melikeaksoy555 commented
> Onerdigim degisiklikler en az kod ile en optimal sonucu almak uzerine uygulanmis degisiklikler. Birden fazla cozum her zaman var olabilir ama en az static deger kullanarak yapilan dizaynlar hedeflenmeli. Bu seni daha az kod yazmak uzerine kosullayacaktir.
> 
> Footer'lar ince ayarlar gerektirebiliyor cunku bir cok elementi ekran kuculdukce az yere sigdirman gerekiyor.
> 
> Genel dizaynin gayet iyi CSS'in oturmus sadece kutu modelini uygularken tecrubeye ihtiyacin var. Ozellikle projenin gereksinimlerini takip edip degiskenleri kullanman ciddiye aldiginin gostergesi. Ayrica clamp gibi ileri seviye responsive cozumlere alisman cok yarar saglayacaktir.
> 
> Onerdigim degisiklikler disinda font renklerini degistirmek icin olabildiginde spesify etmen gerekebilir classlari css icerisinde . ornek `.footer-right ul li a { color:var(--fnt-black)} `
> 
> kolay gelsin

.footer-right ul li a { color:var(--fnt-black)} ekledim. clamp i nereye kullanacağım?

2024-11-09 20:02 UTC, melikeaksoy555 commented on index.html
> +      </div>
.footer-wrapper ekledim, dediğiniz gibi oldu. 

tag'i var ikisini de kapsayan dedigini duyar gibiyim => cidden bunu diyorum:)

2024-11-09 20:08 UTC, melikeaksoy555 commented on style.css
> +  font-family: var(--fnt-family-satoshi);
merhaba, bunları ekledim
  display: flex;
  justify-content: center;

2024-11-09 21:13 UTC, melikeaksoy555 commented on index.html
> +            <a href="#">Career</a>
COMPANY, HELP, FAQ, RESOURCES kısımlarında <ul> ve <li> yapısı kullanıldı. Icon ve image olan kısımda da kullanmak lazım mı?

2024-11-09 22:37 UTC, melikeaksoy555 commented on style.css
> +  max-width: 1240px;
.footer-container yukarıdaki şekilde yapıldı. ne güzel açıklamışsınız teşekkürler. clamp'i .footer-right'ta ve responsiveness ta da kullandım. 6vw dediğimde tam olarak ne yapıyor?

2024-11-09 22:37 UTC, melikeaksoy555 commented on style.css
> +  gap: 113px;
yaptım:)

2024-11-09 22:39 UTC, melikeaksoy555 commented on style.css
> +  margin: auto;
width ve max-width ilave edildi.

2024-11-09 22:43 UTC, melikeaksoy555 commented on style.css
> +  max-width: 149px;
.footer-column {
min-width: 130px; eklendi
} => 4 kisminda hocam burada neyi kast ettiniz?

2024-11-10 00:14 UTC, melikeaksoy555 commented on style.css
> +  margin-bottom: 25px;
width: 90%;
  max-width: 1240px; eklendi

2024-11-10 00:16 UTC, melikeaksoy555 commented on style.css
> +  }
.footer-container {
flex-direction: column;
align-items: center;
}  bu şekilde sadeleştirildi

2024-11-10 00:32 UTC, melikeaksoy555 commented on style.css
> +  margin-bottom: 19px;
margin-bottom: clamp(10px, 4vw, 44px); şeklinde denedim.

2024-11-10 00:44 UTC, melikeaksoy555 commented on style.css
> +    flex-direction: column;
.footer-column {
    width: 40%; bunu anlayamadım.
 @media (max-width: 750px) {
  .footer-right {
    flex-wrap: wrap;
    justify-content: space-around; => bunun yerine  text-align: center; kullandım. 

.footer-bottom {
    flex-direction: column;
  } => buraya da text-align: center ekledim

2024-11-10 00:46 UTC, melikeaksoy555 commented on style.css
> +    text-align: center;
bunu kaldırayım mı emin olamadım, görüntüsü farklı oluyor kaldırınca uygun olur mu

2024-11-10 00:47 UTC, melikeaksoy555 commented on style.css
> +  }
kaldırıldı

2024-11-10 08:21 UTC, melikeaksoy555 commented on index.html
> +        </div>
eklendi

2024-11-10 10:24 UTC, ozcsert commented on style.css
> +  max-width: 1240px;
viewport kisaltmasi, ekran boyutu ne kadarsa onun 6% sini hesapliyor. Dizaynda belirtilen font-size'i bulmak icin deneme yanilma ile bulunmus bir oran. Onu vw ile veriyorum ki dynamic olsun ekran ile beraber kuculup buyuyebilsin(Ta ki belirttigim min ve max stoplara gelene kadar).

2024-11-15 16:40 UTC, ozcsert requested changes
1000px altında 2 sıra olabilirler. 
Newsletter margin-bottom: 50%; girebilirsin

2024-11-16 10:20 UTC, melikeaksoy555 commented
> 1000px altında 2 sıra olabilirler. Newsletter margin-bottom: 50%; girebilirsin

50% ile yapamadım, px ile yaptım. merge'ledim de.

2024-11-17 20:35 UTC, ozcsert requested changes

2024-11-17 20:35 UTC, ozcsert commented on style.css
> +  margin-bottom: -90px;
margin'lerin yuzdelerinin beklendigi gibi calismamasinin sebebi margin yuzdelerini elementin parent'ina gore hesapliyor. O yuzden body'ye nazaran aliyor margin-degerini. 
Bunu cozmenin en temiz yontemi, newsletter section'i ni footer altina alip, 

`  position: absolute;
  top: 0;
  z-index: 10;
  transform: translateY(-50%);`
  degerleriyle oynatmak. 
  
  Ayrica bunu da sizden ekstra rica edecegim, buraya ayrica 
  
  `  width: 90%;
 `
 verelim ki ekran kuculdugunde gorebilelim onu unutmusuz newsletter'i merge ederken.

2024-11-17 20:35 UTC, ozcsert commented on style.css
> +  margin-bottom: -90px;
transform translate'in margin'den farki, yuzde degerlerini elementin kendi boyutuna gore hesaplamasinin yaninda, document akisinda elementin kendi yerini reserve ediyor. Yani margin degeriyle bir elementi oynattigimda eleman onceki yerinde bir bosluk birakmiyor ama translate'te ise sadece gorsel olarak oynatiyor, elemanin eski yerinde bosluk kaliyor. 
position:absolute hem onun icin hem de footer'in akisini bozmasin diye kullandim. Tek problemimiz ayrica diger elementlerle boslugunu ayarlarken biraz el ayari yapacagiz.

2024-11-17 20:35 UTC, ozcsert commented on index.html
> +        </div>
Bu section'in kapama </div> tag'ini unutmusuz. 

Footer altinda alalim bu section'i. Aciklamasini css icerisinde yaptim.

2024-11-26 19:44 UTC, melikeaksoy555 commented
f1d3f7e57e8d6e75bf0d6cabb505cbcc3134b5df nolu commit'e geri dönüş yapmam mümkün müdür?

2024-11-28 14:42 UTC, merged